from . import wallet_inline
from . import chooselang
from . import choosevaluta
from . import callback_data
from . import cancel
from . import chooseGiveTake
from . import pay
from . import adminResult
from . import supportLink